apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  routing:
    localityAwareLoadBalancing: false
  metrics:
    enabledBackend: prometheus-1
    backends:
    - name: prometheus-1
      type: prometheus
      conf:
        skipMTLS: true
  tracing:
    defaultBackend: my-zipkin
    backends:
      - name: my-zipkin
        type: zipkin
        sampling: 100
        conf:
          url: 'http://trace.kuma-trace.svc:9411/api/v2/spans'
  logging:
    backends:
      - name: stdout
        format: '{ "destination": "%KUMA_DESTINATION_SERVICE%", "destinationAddress": "%UPSTREAM_LOCAL_ADDRESS%", "source": "%KUMA_SOURCE_SERVICE%", "sourceAddress": "%KUMA_SOURCE_ADDRESS%", "bytesReceived": "%BYTES_RECEIVED%", "bytesSent": "%BYTES_SENT%"}'
        type: file
        conf:
          path: /dev/stdout
