apiVersion: v1
kind: Namespace
metadata:
  name: main-application
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: main-application
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis"
          ports:
            - name: tcp
              containerPort: 6379
          lifecycle:
            preStop: # delay shutdown to support graceful mesh leave
              exec:
                command: ["/bin/sleep", "30"]
            postStart:
              exec:
                command: ["/usr/local/bin/redis-cli", "set", "zone", "<change-me>"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: main-application
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: main-application
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: "kumahq/kuma-demo"
          env:
            - name: REDIS_HOST
              value: "redis_main-application_svc_6379.mesh"
            - name: REDIS_PORT
              value: "80"
            - name: APP_VERSION
              value: "1.0"
            - name: APP_COLOR
              value: "#efefef"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app
  namespace: main-application
spec:
  selector:
    app: counter-app
  ports:
  - protocol: TCP
    appProtocol: http
    port: 5000
